USE [master]
GO

/****** Object:  Database [ell]    Script Date: 02/12/2017 01:16:27 p. m. ******/
CREATE DATABASE [ell]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ell', FILENAME = N'C:\Users\Victor LG\ell.mdf' , SIZE = 3136KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'ell_log', FILENAME = N'C:\Users\Victor LG\ell_log.ldf' , SIZE = 832KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [ell] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ell].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ell] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ell] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ell] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ell] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ell] SET ARITHABORT OFF 
GO

ALTER DATABASE [ell] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [ell] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [ell] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ell] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ell] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ell] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ell] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ell] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ell] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ell] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ell] SET  ENABLE_BROKER 
GO

ALTER DATABASE [ell] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ell] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ell] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ell] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ell] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ell] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ell] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ell] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [ell] SET  MULTI_USER 
GO

ALTER DATABASE [ell] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ell] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ell] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ell] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [ell] SET  READ_WRITE 
GO


